version: '3.9'

services:
  db-app:
    container_name: database-megaclite
    hostname: db-app
    image: mysql:8.0.40
    environtment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASS}
    ports:
      - ${DATABASE_PORT}:3306
    networks:
      - internals
      
  megaclite-app:
    container_name: megaclite-app
    hostname: megaclite
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLISH_PORT=${APP_PORT}
    environtment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_USER=${DATABASE_USER}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
    ports:
      ${SERVER_PORT}:4000
    networks:
      - internals

networks:
  internals:
    driver: bridge